### ISSUE TITLE
### New Pull Request Checklist

### ISSUE THREAD

**Issue by braybugz** [braybugz/bookish-funicular#1]
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

This fix the issue talked in #https://github.com/SDWebImage/SDWebImage/pull/3262

Also, the main stream compile issue.

__Originally posted by @dreampiggy in https://github.com/SDWebImage/SDWebImage/pull/3277__
